version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: lodedb
    environment:
      POSTGRES_DB: lode_db
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: